dist: trusty
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=1
    MENHIR="20190626"
    PACO="4.0.0"
    COMPCERTR="https://github.com/snu-sf/CompCertR.git"
    BRANCH="v3.6+_adapt"

  matrix:
  - COMPILER="4.07.1"
    TEST_TARGET="8.9.1"
    ARCHI="x86_64-linux"

before_script:
  - ./ci/keep_alive.sh &

install:
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_SLUG
  - opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
  - eval $(opam config env)
  - opam config var root
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y
  - opam install -y --verbose -j ${NJOBS} menhir.${MENHIR} && opam pin add menhir ${MENHIR} -y
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam install -y --verbose -j ${NJOBS} coq-paco.${PACO} && opam pin add coq-paco ${PACO} -y
  - rm -rf ./CompCertR
  - git clone ${COMPCERTR} CompCertR;
  - cd CompCertR
  - git checkout origin/${BRANCH}
  - ./configure ${ARCHI}
  - make -j ${NJOBS}

script:
  - eval $(opam config env)
  - opam config var root
  - cd $TRAVIS_BUILD_DIR/CompCertR
  - rm -rf CompCertM
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git CompCertM
  - cd CompCertM
  - git checkout -qf $TRAVIS_COMMIT
  - make -j ${NJOBS}
